<?php $view->getMetaView()->_tpl_version = '1.0';
$isRO	= (!empty($_REQUEST['report_mode']) && strtolower($_REQUEST['report_mode'])==='r');
$User	= !empty($view->User)	? $view->User	: null;
$LP		= !empty($view->LP)		? $view->LP		: null;
$ReportContent = array();
if (empty($User['success']) || empty($LP['success']))
	echo $view->getBlock('blocks/fer/throwError', array('User'=>$User, 'LP'=>$LP));
elseif (isset($LP['learning_plan_final_evaluation']) && is_array($LP['learning_plan_final_evaluation'])){
	foreach ($LP['learning_plan_final_evaluation'] as $reportField){
		if (!empty($reportField['id'])){
			$ReportContent[$reportField['id']] = $reportField;
		}
	}
}
$LvlScale = array(
		'A1'=>'A1',
		'A2'=>'A2',
		'A3'=>'A3',
		'B1'=>'B1',
		'B2'=>'B2',
		'B3'=>'B3',
		'C1'=>'C1',
		'C2'=>'C2',
		'C3'=>'C3'
);?>
<link rel="stylesheet" type="text/css" href="<?php echo WEB_ROOT?>/css/fer/blended.css">
<div id="report_container">
	<div id="report_subcontainer">
		<h1 class="paragraph-title">
			<?php echo _('Profil')?>
		</h1>
		<div style="background:white;">
			<div class="profile-inline-block">
				<table>
					<tr>
						<td class="profile-label"><?php echo _('Learner:')?></td>
						<td class="profile-value">
							<?php echo !empty($User['firstname']) ? $User['firstname'] : '';?>
							<?php echo !empty($User['lastname']) ? $User['lastname'] : '';?>
						</td>
					</tr>
					<tr>
						<td class="profile-label"><?php echo _('Company:')?></td>
						<td class="profile-value"><?php
						if (!empty($User['fields']) && is_array($User['fields'])){
							foreach ($User['fields'] as $i=>$field){
								if (!empty($field['name']) && !empty($field['value']) && strtolower($field['name'])==='company name'){
									echo $field['value'];
									break;
								}
							}
						}?></td>
					</tr>
					<tr>
						<td class="profile-label"><?php echo _('Date:')?></td>
						<td class="profile-value"><?php echo date('d.m.Y')?></td>
					</tr>
				</table>
			</div>
			<div class="profile-inline-block">
				<table>
					<tr>
						<td class="profile-label"><?php echo _('Title:')?></td>
						<td class="profile-value" colspan="3"><?php
							if (!empty($LP['learning_plan']['path_name']))
								echo _('Final Report for').' '.$LP['learning_plan']['path_name'];
						?></td>
					</tr>
					<tr>
						<td class="profile-label"><?php echo _('Start date:')?></td>
						<td class="profile-value"><?php echo !empty($LP['learning_plan']['learning_plan_user_details']['date_assign']) ? $LP['learning_plan']['learning_plan_user_details']['date_assign'] :
						(
							!empty($LP['learning_plan']['learning_plan_user_details']['date_begin_validity']) ? $LP['learning_plan']['learning_plan_user_details']['date_begin_validity'] : '&nbsp;'
						);?></td>
						<td class="profile-label"><?php echo _('End date:')?></td>
						<td class="profile-value"><?php echo !empty($LP['learning_plan']['learning_plan_user_details']['course_completed']) ? $LP['learning_plan']['learning_plan_user_details']['course_completed'] :
						(
							!empty($LP['learning_plan']['learning_plan_user_details']['date_end_validity']) ? $LP['learning_plan']['learning_plan_user_details']['date_end_validity'] : '&nbsp;'
						);?></td>
					</tr>
					<tr>
						<td class="profile-label"><?php echo _('Total time:')?></td>
						<td class="profile-value"><?php echo !empty($LP['learning_plan']['learning_plan_user_details']['time_spent']) ? $LP['learning_plan']['learning_plan_user_details']['time_spent'] : '';?></td>
					</tr>
				</table>
			</div>
		</div>
		
		<br><br>
		
		<h1 class="paragraph-title">
			<?php echo _('All courses in the learning plan')?>
		</h1>
		<div class="profile-block">
			<h2 class="paragraph-subtitle"><?php echo _('E-learning results:')?></h2>
			<table>
				<tr>
					<td style="width:70%;"></td>
					<td class="profile-value left-bar"><?php echo _('Assessment')?></td>
					<td class="profile-value left-bar"><?php echo _('Time')?></td>
				</tr>
				<?php
				$totalPercentage = $totalTimeSpent = $nbCourses = $nbAttendances = 0;
				if (!empty($LP['learning_plan_courses'])){
					foreach ($LP['learning_plan_courses'] as $ix=>$LPC){
						if (empty($LPC['course_info']['course_name'])||
							strtolower($LPC['course_info']['course_type'])!=='elearning') continue;
						$nbCourses++;
						if (isset($LPC['course_info']['status']) && $LPC['course_info']['status']==2) $nbAttendances++;?>
				<tr class="top-bar">
					<td><?php echo $LPC['course_info']['course_name'];?></td>
					<td class="left-bar"><?php
					if (!empty($LPC['course_user_details']['score_given'])){
						$totalPercentage += (float)$LPC['course_user_details']['score_given'];
						echo str_replace('.', ',',$LPC['course_user_details']['score_given']).'%';
					}?></td>
					<td class="left-bar"><?php //Time spent ???? echo !empty($LPC['course_user_details']['score_given']) ? $LPC['course_user_details']['score_given'] : '';?></td>
				</tr><?php
					}
				}?>
				<tr class="bg-grey">
					<td class="table-total-label"><?php echo _('Total e-learning average')?></td>
					<td class="profile-value left-bar"><?php if ($nbCourses) echo str_replace('.', ',',number_format(($totalPercentage/$nbCourses), 2)).'%';?></td>
					<td class="profile-value left-bar"><?php echo $totalTimeSpent;?></td>
				</tr>
				<tr>
					<td class="table-total-label"><?php echo _('Attendance')?></td>
					<td class="left-bar"><?php echo $nbAttendances.'/'.$nbCourses?></td>
					<td class="left-bar"></td>
				</tr>
			</table>
			
			<br><br><br><br>
			
			<h2 class="paragraph-subtitle"><?php echo _('Session results:')?></h2>
			<table>
				<tr>
					<td style="width:70%;"></td>
					<td class="profile-value left-bar"><?php echo _('Assessment')?></td>
					<td class="profile-value left-bar"><?php echo _('Time')?></td>
				</tr>
				<?php
				$totalPercentage = $totalTimeSpent = $nbCourses = $nbAttendances = 0;
				if (!empty($LP['learning_plan_courses'])){
					foreach ($LP['learning_plan_courses'] as $ix=>$LPC){
						if (empty($LPC['course_info']['course_name'])||
							!in_array(strtolower($LPC['course_info']['course_type']),
								array('videoconference', 'classroom', 'webinar', 'telephone'))) continue;
						$nbCourses++;
						if (isset($LPC['course_info']['status']) && $LPC['course_info']['status']==2) $nbAttendances++;?>
				<tr class="top-bar">
					<td><?php echo $LPC['course_info']['course_name'];?></td>
					<td class="left-bar"><?php
					if (!empty($LPC['course_user_details']['score_given'])){
						$totalPercentage += (float)$LPC['course_user_details']['score_given'];
						echo str_replace('.', ',',$LPC['course_user_details']['score_given']).'%';
					}?></td>
					<td class="left-bar"><?php //Time spent ???? echo !empty($LPC['course_user_details']['score_given']) ? $LPC['course_user_details']['score_given'] : '';?></td>
				</tr><?php
					}
				}?>
				<tr class="bg-grey">
					<td class="table-total-label"><?php echo _('Total skill sessions average')?></td>
					<td class="profile-value left-bar"><?php if ($nbCourses) echo str_replace('.', ',',number_format(($totalPercentage/$nbCourses), 2)).'%';?></td>
					<td class="profile-value left-bar"><?php echo $totalTimeSpent;?></td>
				</tr>
				<tr>
					<td class="table-total-label"><?php echo _('Attendance')?></td>
					<td class="left-bar"><?php echo $nbAttendances.'/'.$nbCourses?></td>
					<td class="left-bar"></td>
				</tr>
			</table>
		</div>
		
		<h1 class="paragraph-title">
			<?php echo _('Evaluator comments');?>
		</h1>
		<div class="profile-block">
			<div class="bg-grey" style="padding:25px;">
				<h2 class="paragraph-subtitle">SKILLS:</h2>
				<?php if (!$isRO){?>
				<textarea name="evaluator_comments" id="evaluator_comments"><?php
				if (!empty($ReportContent['evaluator_comments']['value'])) echo $ReportContent['evaluator_comments']['value'];
				?></textarea>
				<?php }elseif (!empty($ReportContent['evaluator_comments']['value'])){?>
				<div>
					<?php echo $ReportContent['evaluator_comments']['value'];?>
				</div>
				<?php }?>
			</div>
		</div>
		
		<br><br><br>
		
		<h1 class="paragraph-title">SKILL’S LEVEL</h1>
		<div class="profile-block">
			<h2 class="paragraph-subtitle">SKILLS:</h2>
			<br>
			<div>Learner's current level for each of the skills below:</div>
			<br>
			<div class="level-scale-container">
				<?php foreach (array(
						'listening_current_level'	=>'Listening:',
						'speaking_current_level'	=>'Speaking:',
						'reading_current_level'		=>'Reading:',
						'spoken_production_current_level'	=>'Spoken production:',
						'spoken_interaction_current_level'	=>'Spoken interaction:',
				) as $key=>$text){?>
				<div class="level-spacing">
					<label for="<?php echo $key?>" class="level-label"><?php echo $text?></label>
					<?php if (!$isRO){?>
					<select id="<?php echo $key?>" name="<?php echo $key?>" class="level-scale bg-grey">
						<option></option>
						<?php foreach ($LvlScale as $lK=>$lT){?>
						<option value="<?php echo $lK?>"<?php
							if (!empty($ReportContent[$key]['value']) && $ReportContent[$key]['value']===$lK)
								echo ' selected';
						?>><?php echo $lT?></option>
						<?php }?>
					</select>
					<?php }elseif (!empty($ReportContent[$key]['value'])){?>
					<span class="profile-value"><?php echo $ReportContent[$key]['value'];?></span>
					<?php }?>
				</div>
				<?php }?>
			</div>
		</div>
		
		<br><br>
		
		<h1 class="paragraph-title">LEARNER’S LEVEL</h1>
		<div class="profile-block bg-grey">
			<div>Learner's overall current and recommended levels:</div>
			<div class="level-scale-container">
				<?php foreach (array(
						'learner_current_level'		=>'Current level:',
						'learner_recommended_level'	=>'Recommended level:',
				) as $key=>$text){?>
				<div class="level-spacing">
					<label for="<?php echo $key?>" class="level-label"><?php echo $text?></label>
					<?php if (!$isRO){?>
					<select id="<?php echo $key?>" name="<?php echo $key?>" class="level-scale">
						<option></option>
						<?php foreach ($LvlScale as $lK=>$lT){?>
						<option value="<?php echo $lK?>"<?php
							if (!empty($ReportContent[$key]['value']) && $ReportContent[$key]['value']===$lK)
								echo ' selected';
						?>><?php echo $lT?></option>
						<?php }?>
					</select>
					<?php }elseif (!empty($ReportContent[$key]['value'])){?>
					<span class="profile-value"><?php echo $ReportContent[$key]['value'];?></span>
					<?php }?>
				</div>
				<?php }?>
				<div class="level-spacing">
					<span class="level-label">PROGRESS:</span>
					<label for="progress_satisfactory" class="radio-label">
						<input type="radio" value="1" id="progress_satisfactory" name="progress_satisfactory"<?php
						if (!empty($ReportContent['progress_satisfactory']) && (int)$ReportContent['progress_satisfactory']===1) echo ' selected';?> />
						&nbsp;
						Satisfactory
					</label>
					&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
					<label for="progress_unsatisfactory" class="radio-label">
						<input type="radio" value="0" id="progress_unsatisfactory" name="progress_satisfactory"<?php
						if (!empty($ReportContent['progress_satisfactory']) && (int)$ReportContent['progress_satisfactory']===0) echo ' selected';?> />
						&nbsp;
						Unsatisfactory
					</label>
				</div>
			</div>
		</div>
	</div>
</div>