<?php $view->getMetaView()->_tpl_version = '1.0';
$isRO	= (!empty($_REQUEST['report_mode']) && strtolower($_REQUEST['report_mode'])==='r');
$User	= !empty($view->User)	? $view->User	: null;
$LP		= !empty($view->LP)		? $view->LP		: null;
$ReportContent = array();
if (empty($User['success']) || empty($LP['success']))
	echo $view->getBlock('blocks/fer/throwError', array('User'=>$User, 'LP'=>$LP));
elseif (isset($LP['learning_plan_final_evaluation']) && is_array($LP['learning_plan_final_evaluation'])){
	foreach ($LP['learning_plan_final_evaluation'] as $reportField){
		if (!empty($reportField['id'])){
			$ReportContent[$reportField['id']] = $reportField;
		}
	}
}
$LvlScale = array(
		'A1'=>'A1',
		'A2'=>'A2',
		'A3'=>'A3',
		'B1'=>'B1',
		'B2'=>'B2',
		'B3'=>'B3',
		'C1'=>'C1',
		'C2'=>'C2',
		'C3'=>'C3'
);
$style = array(
	'#report_container'		=>'background: white; text-align: left; padding: 20px 0; font-family: Arial; font-size: 13px;',
	'#report_subcontainer'	=>'margin: auto; width: 98%; font-family: Arial;',
	'.page'					=>'size:A4;',
	'.paragraph-title'		=>'text-transform: uppercase; margin: 15px 0; font-weight: normal; font-size: 16px; font-family: Arial;',
	'.paragraph-subtitle'	=>'font-size: 14px; text-transform: uppercase; font-weight: normal; font-family: Arial;',
	'.profile-block'		=>'padding: 2.5%; width: 95%; margin: auto; font-family: Arial;',
	'table'					=>'border-collapse: collapse; width: 100%; font-family: Arial;',
	'td'					=>'white-space: nowrap; padding: 10px 0; font-family: Arial;',
	'.profile-block td'		=>'padding: 15px 0; white-space: normal;',
	'.top-bar'				=>'border-top: 1px solid rgb(118,118,118);',
	'.left-bar'				=>'border-left: 1px solid rgb(118,118,118);',
	'.profile-block .left-bar'=>'padding-left: 20px; font-family: Arial;',
	'.profile-label'		=>'text-transform: uppercase; font-size: 14px;',
	'.profile-value'		=>'font-weight: bold; font-family: Arial;',
	'.bg-grey'				=>'background: rgb(233,233,233); font-family: Arial;',
	'.table-total-label'	=>'text-align: right; text-transform: uppercase; padding-right: 25px; font-family: Arial;',
	'#evaluator_comments'	=>'width: 100%; min-width: 100%; max-width: 100%; height: 120px; border: 1px solid rgb(225,225,225); background: transparent; padding: 10px; font-family: Arial;',
	'.level-scale-container'=>'width: 95%; margin: auto; font-family: Arial;',
	'.level-spacing'		=>'margin: 15px;',
	'.level-label'			=>'display: inline-block; width: 29%; font-size: 13px; text-transform: uppercase; font-family: Arial;',
	'.level-scale'			=>'display: inline-block; width: 70%; height: 30px; background: white; border: none; padding-left: 20px; font-family: Arial;',
	'.radio-label'			=>'font-size: 13px; cursor: pointer; font-family: Arial;',
);
?>
<div id="report_container" style="<?php echo $style['#report_container']?>">
	<div id="report_subcontainer" style="<?php echo $style['#report_subcontainer']?>">
	<div style="<?php echo $style['.page']?>">
		<h1 class="paragraph-title" style="<?php echo $style['.paragraph-title']?>">
			<?php echo _('Profil')?>
		</h1>
		<div style="<?php echo $style['.profile-block']?>">
			<table style="<?php echo $style['table']?>">
				<tr>
					<td class="profile-label" style="<?php echo $style['td'].$style['.profile-label']?>"><?php echo _('Learner:')?></td>
					<td class="profile-value" style="<?php echo $style['td'].$style['.profile-value']?>">
						<?php echo !empty($User['firstname']) ? $User['firstname'].'&nbsp;' : '';?>
						<?php echo !empty($User['lastname']) ? $User['lastname'] : '';?>
					</td>
					<td colspan="4">
						<span class="profile-label" style="<?php echo $style['td'].$style['.profile-label']?>">Title:</span>
						&nbsp;&nbsp;&nbsp;
						<span class="profile-value" style="<?php echo $style['td'].$style['.profile-value']?>"><?php
						if (!empty($LP['learning_plan']['path_name']))
							echo _('Final Report for').' '.$LP['learning_plan']['path_name'];?></span>
					</td>
				</tr>
				<tr>
					<td class="profile-label" style="<?php echo $style['td'].$style['.profile-label']?>"><?php echo _('Company:')?></td>
					<td class="profile-value" style="<?php echo $style['td'].$style['.profile-value']?>"><?php
					if (!empty($User['fields']) && is_array($User['fields'])){
						foreach ($User['fields'] as $i=>$field){
							if (!empty($field['name']) && !empty($field['value']) && strtolower($field['name'])==='company name'){
								echo $field['value'];
								break;
							}
						}
					}?></td>
					<td class="profile-label" style="<?php echo $style['td'].$style['.profile-label']?>"><?php echo _('Start date:')?></td>
					<td class="profile-value" style="<?php echo $style['td'].$style['.profile-value']?>"><?php echo !empty($LP['learning_plan']['learning_plan_user_details']['date_assign']) ? $LP['learning_plan']['learning_plan_user_details']['date_assign'] :
					(
						!empty($LP['learning_plan']['learning_plan_user_details']['date_begin_validity']) ? $LP['learning_plan']['learning_plan_user_details']['date_begin_validity'] : '&nbsp;'
					);?></td>
					<td class="profile-label" style="<?php echo $style['td'].$style['.profile-label']?>"><?php echo _('End date:')?></td>
					<td class="profile-value" style="<?php echo $style['td'].$style['.profile-value']?>"><?php echo !empty($LP['learning_plan']['learning_plan_user_details']['course_completed']) ? $LP['learning_plan']['learning_plan_user_details']['course_completed'] :
					(
						!empty($LP['learning_plan']['learning_plan_user_details']['date_end_validity']) ? $LP['learning_plan']['learning_plan_user_details']['date_end_validity'] : '&nbsp;'
					);?></td>
				</tr>
				<tr>
					<td class="profile-label" style="<?php echo $style['td'].$style['.profile-label']?>"><?php echo _('Date:')?></td>
					<td class="profile-value" style="<?php echo $style['td'].$style['.profile-value']?>"><?php echo date('d.m.Y')?></td>
					<td class="profile-label" style="<?php echo $style['td'].$style['.profile-label']?>"><?php echo _('Total time:')?></td>
					<td class="profile-value" style="<?php echo $style['td'].$style['.profile-value']?>"><?php echo !empty($LP['learning_plan']['learning_plan_user_details']['time_spent']) ? $LP['learning_plan']['learning_plan_user_details']['time_spent'] : '';?></td>
				</tr>
			</table>
		</div>
		
		<br><br>
		
		<h1 class="paragraph-title" style="<?php echo $style['.paragraph-title']?>">
			<?php echo _('All courses in the learning plan')?>
		</h1>
		<div class="profile-block" style="<?php echo $style['.profile-block']?>">
			<h2 class="paragraph-subtitle" style="<?php echo $style['.paragraph-subtitle']?>"><?php echo _('E-learning results:')?></h2>
			<table style="<?php echo $style['table']?>">
				<tr>
					<td style="<?php echo $style['td'].$style['.profile-block td']?>width:64%;"></td>
					<td class="profile-value left-bar" style="<?php echo $style['td'].$style['.profile-value'].
						$style['.left-bar'].$style['.profile-block .left-bar']?>width:18%;"><?php echo _('Assessment')?></td>
					<td class="profile-value left-bar" style="<?php echo $style['td'].$style['.profile-value'].
						$style['.left-bar'].$style['.profile-block .left-bar']?>width:18%;"><?php echo _('Time')?></td>
				</tr>
				<?php
				$totalPercentage = $totalTimeSpent = $nbCourses = $nbAttendances = 0;
				if (!empty($LP['learning_plan_courses'])){
					foreach ($LP['learning_plan_courses'] as $ix=>$LPC){
						if (empty($LPC['course_info']['course_name'])||
							strtolower($LPC['course_info']['course_type'])!=='elearning') continue;
						$nbCourses++;
						if (isset($LPC['course_info']['status']) && $LPC['course_info']['status']==2) $nbAttendances++;?>
				<tr>
					<td class="top-bar" style="<?php echo $style['td'].$style['.profile-block td'].$style['.top-bar']?>"><?php echo $LPC['course_info']['course_name'];?></td>
					<td class="left-bar top-bar" style="<?php echo $style['td'].$style['.profile-block td'].$style['.left-bar'].
						$style['.top-bar'].$style['.profile-block .left-bar']?>"><?php
					if (!empty($LPC['course_user_details']['score_given'])){
						$totalPercentage += (float)$LPC['course_user_details']['score_given'];
						echo str_replace('.', ',',$LPC['course_user_details']['score_given']).'%';
					}?></td>
					<td class="left-bar top-bar" style="<?php echo $style['td'].$style['.profile-block td'].$style['.left-bar'].$style['.top-bar'].$style['.profile-block .left-bar']?>"><?php //Time spent ???? echo !empty($LPC['course_user_details']['score_given']) ? $LPC['course_user_details']['score_given'] : '';?></td>
				</tr><?php
					}
				}?>
				<tr class="bg-grey" style="<?php echo $style['.bg-grey']?>">
					<td class="table-total-label" style="<?php echo $style['td'].$style['.profile-block td'].$style['.table-total-label']?>"><?php echo _('Total e-learning average')?></td>
					<td class="profile-value left-bar" style="<?php echo $style['td'].$style['.profile-block td'].$style['.left-bar'].
						$style['.profile-value'].$style['.profile-block .left-bar']?>"><?php if ($nbCourses) echo str_replace('.', ',',number_format(($totalPercentage/$nbCourses), 2)).'%';?></td>
					<td class="profile-value left-bar" style="<?php echo $style['td'].$style['.profile-block td'].$style['.left-bar'].
						$style['.profile-value'].$style['.profile-block .left-bar']?>"><?php echo $totalTimeSpent;?></td>
				</tr>
				<tr>
					<td class="table-total-label" style="<?php echo $style['td'].$style['.profile-block td'].$style['.table-total-label']?>"><?php echo _('Attendance')?></td>
					<td class="left-bar" style="<?php echo $style['td'].$style['.profile-block td'].$style['.left-bar'].$style['.profile-block .left-bar']?>"><?php echo $nbAttendances.'/'.$nbCourses?></td>
					<td class="left-bar" style="<?php echo $style['td'].$style['.profile-block td'].$style['.left-bar'].$style['.profile-block .left-bar']?>"></td>
				</tr>
			</table>
		</div>
	</div>		<!-- <br><br><br><br> -->
		
	<div style="<?php echo $style['.page']?>">
		<div class="profile-block" style="<?php echo $style['.profile-block']?>">
			<h2 class="paragraph-subtitle" style="<?php echo $style['.paragraph-subtitle']?>"><?php echo _('Session results:')?></h2>
			<table style="<?php echo $style['table']?>">
				<tr>
					<td style="<?php echo $style['td'].$style['.profile-block td']?>width:64%;"></td>
					<td class="profile-value left-bar" style="<?php echo $style['td'].$style['.profile-block td'].$style['profile-value'].
						$style['.left-bar'].$style['.profile-block .left-bar']?>width:18%;"><?php echo _('Assessment')?></td>
					<td class="profile-value left-bar" style="<?php echo $style['td'].$style['.profile-block td'].$style['profile-value'].
						$style['.left-bar'].$style['.profile-block .left-bar']?>width:18%;"><?php echo _('Time')?></td>
				</tr>
				<?php
				$totalPercentage = $totalTimeSpent = $nbCourses = $nbAttendances = 0;
				if (!empty($LP['learning_plan_courses'])){
					foreach ($LP['learning_plan_courses'] as $ix=>$LPC){
						if (empty($LPC['course_info']['course_name']) ||
							!in_array(strtolower($LPC['course_info']['course_type']), array('videoconference', 'classroom', 'webinar', 'telephone')))
						{
							continue;
						}
						$nbCourses++;
						if (isset($LPC['course_info']['status']) && $LPC['course_info']['status']==2) $nbAttendances++;?>
				<tr>
					<td class="top-bar" style="<?php echo $style['td'].$style['.profile-block td'].$style['.top-bar']?>"><?php echo $LPC['course_info']['course_name'];?></td>
					<td class="top-bar left-bar" style="<?php echo $style['td'].$style['.profile-block td'].$style['.top-bar'].
						$style['.left-bar'].$style['.profile-block .left-bar']?>"><?php
					if (!empty($LPC['course_user_details']['score_given'])){
						$totalPercentage += (float)$LPC['course_user_details']['score_given'];
						echo str_replace('.', ',',$LPC['course_user_details']['score_given']).'%';
					}?></td>
					<td class="top-bar left-bar" style="<?php echo $style['td'].$style['.profile-block td'].$style['.top-bar'].
						$style['.left-bar'].$style['.profile-block .left-bar']?>"><?php //Time spent ???? echo !empty($LPC['course_user_details']['score_given']) ? $LPC['course_user_details']['score_given'] : '';?></td>
				</tr><?php
					}
				}?>
				<tr class="bg-grey" style="<?php echo $style['.bg-grey']?>">
					<td class="table-total-label" style="<?php echo $style['td'].$style['.profile-block td'].$style['.table-total-label']?>"><?php echo _('Total skill sessions average')?></td>
					<td class="profile-value left-bar" style="<?php echo $style['td'].$style['.profile-block td'].$style['.left-bar'].
						$style['.profile-value'].$style['.profile-block .left-bar']?>"><?php if ($nbCourses) echo str_replace('.', ',',number_format(($totalPercentage/$nbCourses), 2)).'%';?></td>
					<td class="profile-value left-bar" style="<?php echo $style['td'].$style['.profile-block td'].$style['.left-bar'].
						$style['.profile-value'].$style['.profile-block .left-bar']?>"><?php echo $totalTimeSpent;?></td>
				</tr>
				<tr>
					<td class="table-total-label" style="<?php echo $style['td'].$style['.profile-block td'].$style['.table-total-label']?>"><?php echo _('Attendance')?></td>
					<td class="left-bar" style="<?php echo $style['td'].$style['.profile-block td'].$style['.left-bar'].$style['.profile-block .left-bar']?>"><?php echo $nbAttendances.'/'.$nbCourses?></td>
					<td class="left-bar" style="<?php echo $style['td'].$style['.profile-block td'].$style['.left-bar'].$style['.profile-block .left-bar']?>"></td>
				</tr>
			</table>
		</div>
	</div>
	<div style="<?php echo $style['.page']?>">
		<h1 class="paragraph-title" style="<?php echo $style['.paragraph-title']?>">
			<?php echo _('Evaluator comments');?>
		</h1>
		<div class="profile-block bg-grey" style="<?php echo $style['.profile-block'].$style['.bg-grey']?>">
			<h2 class="paragraph-subtitle" style="<?php echo $style['.paragraph-subtitle']?>">SKILLS:</h2>
			<?php if (!$isRO){?>
			<textarea name="evaluator_comments" id="evaluator_comments" style="<?php echo $style['#evaluator_comments']?>"><?php
			if (!empty($ReportContent['evaluator_comments']['value']))
				echo $ReportContent['evaluator_comments']['value'];
			?></textarea>
			<?php }elseif (!empty($ReportContent['evaluator_comments']['value'])){?>
			<div>
				<?php echo nl2br($ReportContent['evaluator_comments']['value']);?>
			</div>
			<?php }?>
		</div>
		
		<br><br><br>
		
		<h1 class="paragraph-title" style="<?php echo $style['.paragraph-title']?>">SKILL’S LEVEL</h1>
		<div class="profile-block" style="<?php echo $style['.profile-block']?>">
			<h2 class="paragraph-subtitle" style="<?php echo $style['.paragraph-subtitle']?>">SKILLS:</h2>
			<br>
			<div>Learner's current level for each of the skills below:</div>
			<br>
			<div class="level-scale-container" style="<?php echo $style['.level-scale-container']?>">
				<?php foreach (array(
						'listening_current_level'	=>'Listening:',
						'speaking_current_level'	=>'Speaking:',
						'reading_current_level'		=>'Reading:',
						'spoken_production_current_level'	=>'Spoken production:',
						'spoken_interaction_current_level'	=>'Spoken interaction:',
				) as $key=>$text){?>
				<div class="level-spacing" style="<?php echo $style['.level-spacing']?>">
					<label for="<?php echo $key?>" class="level-label" style="<?php echo $style['.level-label']?>"><?php echo $text?></label>
					<?php if (!$isRO){?>
					<select id="<?php echo $key?>" name="<?php echo $key?>" class="level-scale bg-grey"
						style="<?php echo $style['.level-scale'].$style['.bg-grey']?>">
						<option></option>
						<?php foreach ($LvlScale as $lK=>$lT){?>
						<option value="<?php echo $lK?>"<?php
							if (!empty($ReportContent[$key]['value']) && $ReportContent[$key]['value']===$lK)
								echo ' selected';
						?>><?php echo $lT?></option>
						<?php }?>
					</select>
					<?php }elseif (!empty($ReportContent[$key]['value'])){?>
					<span class="profile-value" style="<?php echo $style['.profile-value']?>"><?php echo $ReportContent[$key]['value'];?></span>
					<?php }?>
				</div>
				<?php }?>
			</div>
		</div>
	</div>
	
	<br><br>
	<div style="<?php echo $style['.page']?>">
		<h1 class="paragraph-title" style="<?php echo $style['.paragraph-title']?>">LEARNER’S LEVEL</h1>
		<div class="profile-block bg-grey" style="<?php echo $style['.profile-block'].$style['.bg-grey']?>">
			<div>Learner's overall current and recommended levels:</div>
			<div class="level-scale-container" style="<?php echo $style['.level-scale-container']?>">
				<?php foreach (array(
						'learner_current_level'		=>'Current level:',
						'learner_recommended_level'	=>'Recommended level:',
				) as $key=>$text){?>
				<div class="level-spacing" style="<?php echo $style['.level-spacing']?>">
					<label for="<?php echo $key?>" class="level-label" style="<?php echo $style['.level-label']?>"><?php echo $text?></label>
					<?php if (!$isRO){?>
					<select id="<?php echo $key?>" name="<?php echo $key?>" class="level-scale" style="<?php echo $style['.level-scale']?>">
						<option></option>
						<?php foreach ($LvlScale as $lK=>$lT){?>
						<option value="<?php echo $lK?>"<?php
							if (!empty($ReportContent[$key]['value']) && $ReportContent[$key]['value']===$lK)
								echo ' selected';
						?>><?php echo $lT?></option>
						<?php }?>
					</select>
					<?php }elseif (!empty($ReportContent[$key]['value'])){?>
					<span class="profile-value" style="<?php echo $style['.profile-value']?>"><?php echo $ReportContent[$key]['value'];?></span>
					<?php }?>
				</div>
				<?php }?>
				<div class="level-spacing" style="<?php echo $style['.level-spacing']?>">
					<span class="level-label" style="<?php echo $style['.level-label']?>">PROGRESS:</span>
					<label for="progress_satisfactory" class="radio-label" style="<?php echo $style['.radio-label']?>">
						<input type="radio" value="1" id="progress_satisfactory" name="progress_satisfactory"<?php
						if (!empty($ReportContent['progress_satisfactory']) && (int)$ReportContent['progress_satisfactory']===1) echo ' selected';?> />
						&nbsp;
						Satisfactory
					</label>
					&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
					<label for="progress_unsatisfactory" class="radio-label" style="<?php echo $style['.radio-label']?>">
						<input type="radio" value="0" id="progress_unsatisfactory" name="progress_satisfactory"<?php
						if (!empty($ReportContent['progress_satisfactory']) && (int)$ReportContent['progress_satisfactory']===0) echo ' selected';?> />
						&nbsp;
						Unsatisfactory
					</label>
				</div>
			</div>
		</div>
	</div>
	</div>
</div>