<?php
$view->getMetaView()->_tpl_version = '1.0';//Defining this template version

$isRO = (!empty($_REQUEST['report_mode']) && strtolower($_REQUEST['report_mode'])==='r');//Is it on read only mode?

$LvlScale = $ReportContent = array();//Declare some useful array

$LP = !empty($view->RpData) ? $view->RpData : null;//Set full data

if (empty($LP['success']))
	echo $view->getBlock('blocks/fer/throwError', array('Data'=>$LP));//Display error block
elseif (isset($LP['learning_plan_final_evaluation']) && is_array($LP['learning_plan_final_evaluation'])){
	foreach ($LP['learning_plan_final_evaluation'] as $reportField){
		if (!empty($reportField['id']))
			$ReportContent[$reportField['id']] = $reportField;//Fill in the array that contains the custom fields for the report
	}
}
$User = !empty($LP['user_profile']) ? $LP['user_profile'] : null;
if (!empty($LP['level_scale'])){
	foreach ($LP['level_scale'] as $i=>$lvl)
		$LvlScale[$lvl['id']] = $lvl['name'];
}
/**
 * Unfortunately, we need to set all the CSS inline. Using a PHP hack
 */
$style = array(
	'#report_container'		=>'background:white;text-align:left;padding: 20px 0;font-family:Arial;font-size: 13px;',
	'#report_subcontainer'	=>'margin:auto;width:98%;font-family:Arial;',
	'#evaluator_comments'	=>'background:white;width:100%;min-width:100%;max-width:100%;height:120px;border:1px solid rgb(225,225,225);padding:10px;font-family:Arial;',
	'.paragraph-title'		=>'text-transform:uppercase;margin:15px 0;font-weight:normal;font-size:16px;font-family:Arial;',
	'.paragraph-subtitle'	=>'font-size:14px;text-transform:uppercase;margin:0;margin-bottom:15px;font-weight:bold;color:black;font-family:Arial;',
	'.profile-block'		=>'padding:2.5%;width:95%;margin:auto;font-family:Arial;',
	'table'					=>'border-collapse:collapse;width:100%;font-family:Arial;',
	'td'					=>'padding:10px 5px;font-size:13px;font-family:Arial;',
	'.profile-label'		=>'width:100px;text-transform:uppercase;font-size:13px;',
	'.profile-value'		=>'font-weight:bold;font-family:Arial;font-size:12px;',
	'.bg-grey'				=>'background:rgb(233,233,233);font-family: Arial;',
	'.level-scale-container'=>'background:rgb(237,237,237);padding: 25px;font-family:Arial;',
	'.level-spacing'		=>'margin:15px;',
	'.level-label'			=>'display:inline-block;width:29%;font-size:13px;text-transform:uppercase;color:black;font-family:Arial;',
	'.level-scale'			=>'display:inline-block;width:70%;height:30px;background:white;border:none;padding-left:20px;font-family:Arial;',
	'.skills-aptitude-block'=>'position:relative;min-height:50px;padding:30px 0px;white-space:normal;border-bottom:1px solid rgb(50,50,50);clear:both;',
	'.skills-aptitude-number'=>'background:rgb(87,87,87);display:block;width:55px;line-height:55px;height:55px;font-size:26px;font-weight:bold;'.
								'text-align:center;border-radius:40px;color:white;margin:auto;',
	'.skills-aptitude-title'=>'font-weight:bold;font-size:14px;margin:0;text-transform:uppercase;',
	'.skills-aptitude-text'	=>'font-style:italic;font-size:13px;margin-top:5px;',
	'.float-first-block'	=>'float:left;width:120px;overflow:hidden;white-space:nowrap;',
	'.float-second-block'	=>'float:left;max-width:75%;',
);?>
<div id="report_container" style="<?php echo $style['#report_container']?>">
	<div id="report_subcontainer" style="<?php echo $style['#report_subcontainer']?>">
		<h1 class="paragraph-title" style="<?php echo $style['.paragraph-title']?>">
			Profil
		</h1>
		<div style="background:white;">
			<table style="<?php echo $style['table']?>">
				<tr>
					<td class="profile-label" style="<?php echo $style['td'].$style['.profile-label']?>">Learner:</td>
					<td class="profile-value" style="<?php echo $style['td'].$style['.profile-value']?>">
						<?php echo !empty($User['firstname']) ? $User['firstname'].'&nbsp;' : '';?>
						<?php echo !empty($User['lastname']) ? $User['lastname'] : '';?>
					</td>
					<td class="profile-label" style="<?php echo $style['td'].$style['.profile-label']?>">LEVEL:</td>
					<td class="profile-value" colspan="3" style="<?php echo $style['td'].$style['.profile-value']?>"><?php
						$level = null;
						if (!empty($User['fields']) && is_array($User['fields'])){
							foreach ($User['fields'] as $i=>$field){
								if (!empty($field['name']) && !empty($field['value']) && in_array(strtolower($field['name']), array('acquired level', 'recommended level'))){
									$level = $field['value'];
									break;
								}
							}
						}
						echo !empty($LvlScale[$level]) ? $LvlScale[$level] : 'Unmatched level for ID '.$level;?>
					</td>
				</tr>
				<tr>
					<td class="profile-label" style="<?php echo $style['td'].$style['.profile-label']?>">Company:</td>
					<td class="profile-value" style="<?php echo $style['td'].$style['.profile-value']?>"><?php
					if (!empty($User['fields']) && is_array($User['fields'])){
						foreach ($User['fields'] as $i=>$field){
							if (!empty($field['name']) && !empty($field['value']) && strtolower($field['name'])==='company name'){
								echo $field['value'];
								break;
							}
						}
					}?></td>
					<td class="profile-label" style="<?php echo $style['td'].$style['.profile-label']?>">Start date:</td>
					<td class="profile-value" style="<?php echo $style['td'].$style['.profile-value']?>"><?php
						$date_begin = !empty($LP['learning_plan_user_details']['date_assign']) ? $LP['learning_plan_user_details']['date_assign'] :
							(!empty($LP['learning_plan_user_details']['date_begin_validity']) ? $LP['learning_plan_user_details']['date_begin_validity'] : null);
						echo $date_begin ? date('d.m.Y', strtotime($date_begin)) : '&nbsp;';?></td>
					<td class="profile-label" style="<?php echo $style['td'].$style['.profile-label']?>">End date:</td>
					<td class="profile-value" style="<?php echo $style['td'].$style['.profile-value']?>"><?php
						$date_end = !empty($LP['learning_plan_user_details']['course_completed']) ? $LP['learning_plan_user_details']['course_completed'] :
							(!empty($LP['learning_plan_user_details']['date_end_validity']) ? $LP['learning_plan_user_details']['date_end_validity'] : null);
						echo $date_end ? date('d.m.Y', strtotime($date_end)) : '&nbsp;';?></td>
				</tr>
				<tr>
					<td class="profile-label" style="<?php echo $style['td'].$style['.profile-label']?>">Date:</td>
					<td class="profile-value" style="<?php echo $style['td'].$style['.profile-value']?>"><?php echo date('d.m.Y')?></td>
					<td class="profile-label" style="<?php echo $style['td'].$style['.profile-label']?>">Total time:</td>
					<td class="profile-value" style="<?php echo $style['td'].$style['.profile-value']?>"><?php
						//Should be in seconds
						$totaltime = !empty($LP['learning_plan_user_details']['time_spent']) ? (int)$LP['learning_plan_user_details']['time_spent'] : 0;
						if ($totaltime){
							$hrs = floor($totaltime / 3600);
							if (strlen($hrs)===1) $hrs = '0'.$hrs;
							$mns = floor(($totaltime / 60) % 60);
							if (strlen($mns)===1) $mns = '0'.$mns;
							$scs = $totaltime % 60;
							if (strlen($scs)===1) $scs = '0'.$scs;
							echo $hrs.':'.$mns.':'.$scs;
						}?></td>
				</tr>
			</table>
		</div>
		
		<br><br><br>
		
		<h1 class="paragraph-title" style="<?php echo $style['.paragraph-title']?>">
			Language Skills Aptitude Test
		</h1>
		<?php $NA = $IT = $WT = $ST = null;
		foreach ($LP['learning_plan_courses'] as $Course){
			if (!empty($Course['course_info']['course_name'])){
				$coursename = strtolower($Course['course_info']['course_name']);
				if (stripos($coursename, 'needs')!==false)
					$NA = $Course;
				elseif (stripos($coursename, 'written')!==false)
					$WT = $Course;
				elseif (stripos($coursename, 'itest')!==false)
					$IT = $Course;
				elseif (stripos($coursename, 'speaking')!==false)
					$ST = $Course;
			}
		}?>
		<div class="skills-aptitude-block" style="<?php echo $style['.skills-aptitude-block']?>">
			<div style="<?php echo $style['.float-first-block']?>">
				<div class="skills-aptitude-number" style="<?php echo $style['.skills-aptitude-number']?>">
					1
				</div>
			</div>
			<div style="<?php echo $style['.float-second-block']?>">
				<h2 class="skills-aptitude-title" style="<?php echo $style['.skills-aptitude-title']?>">Needs Analysis</h2>
				<div class="skills-aptitude-text" style="<?php echo $style['.skills-aptitude-text']?>">
					<?php if (!empty($NA['course_user_details']['date_completed'])){?>
					<b>Completed <?php echo date('d.m.Y', strtotime($NA['course_user_details']['date_completed']))?></b>
					&nbsp;&nbsp;&nbsp;&nbsp;
					<a href="#">See all the answers</a>
					<?php }else{?>
					Elearning DOCEBO “Survey”
					<?php }?>
				</div>
			</div>
			<div style="clear:both"></div>
		</div>
		<div class="skills-aptitude-block" style="<?php echo $style['.skills-aptitude-block']?>">
			<div style="<?php echo $style['.float-first-block']?>">
				<div class="skills-aptitude-number" style="<?php echo $style['.skills-aptitude-number']?>">
					2
				</div>
			</div>
			<div style="<?php echo $style['.float-second-block']?>">
				<h2 class="skills-aptitude-title" style="<?php echo $style['.skills-aptitude-title']?>">Written test</h2>
				<div class="skills-aptitude-text" style="<?php echo $style['.skills-aptitude-text']?>">
					<?php if (!empty($WT['course_user_details']['date_completed'])){?>
					<b>Completed <?php echo date('d.m.Y', strtotime($WT['course_user_details']['date_completed']))?></b>
					<br><br>
					<i>Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l'imprimerie depuis les années 1500, quand un peintre anonyme assembla ensemble des morceaux de texte pour réaliser un livre spécimen de polices de texte. Il n'a pas fait que survivre cinq siècles, mais s'est aussi adapté à la bureautique informatique, sans que son contenu n'en soit modifié. Il a été popularisé dans les années 1960 grâce à la vente de feuilles Letraset contenant des passages du Lorem Ipsum, et, plus récemment, par son inclusion dans des applications de mise en page de texte, comme Aldus PageMaker.</i>
					<?php }else{?>
					Elearning DOCEBO “Test”
					<?php }?>
				</div>
			</div>
			<div style="clear:both"></div>
		</div>
		<div class="skills-aptitude-block" style="<?php echo $style['.skills-aptitude-block']?>">
			<div style="<?php echo $style['.float-first-block']?>">
				<div class="skills-aptitude-number" style="<?php echo $style['.skills-aptitude-number']?>">
					3
				</div>
			</div>
			<div style="<?php echo $style['.float-second-block']?>">
				<h2 class="skills-aptitude-title" style="<?php echo $style['.skills-aptitude-title']?>">iTest</h2>
				<div class="skills-aptitude-text" style="<?php echo $style['.skills-aptitude-text']?>">
					<?php if (!empty($IT['course_user_details']['date_completed'])){?>
					<b>Completed <?php echo date('d.m.Y', strtotime($IT['course_user_details']['date_completed']))?></b>
					&nbsp;&nbsp;&nbsp;&nbsp;
					<a href="#">See all the answers</a>
					<br><br>
					<i>Estimated level is <b><?php echo '...'?></b></i>
					<?php }else{?>
					Elearning SCORM Content
					<?php }?>
				</div>
			</div>
			<div style="clear:both"></div>
		</div>
		<div class="skills-aptitude-block" style="<?php echo $style['.skills-aptitude-block']?>">
			<div style="<?php echo $style['.float-first-block']?>">
				<div class="skills-aptitude-number" style="<?php echo $style['.skills-aptitude-number']?>">
					4
				</div>
			</div>
			<div style="<?php echo $style['.float-second-block']?>">
				<h2 class="skills-aptitude-title" style="<?php echo $style['.skills-aptitude-title']?>">Speaking Test</h2>
				<div class="skills-aptitude-text" style="<?php echo $style['.skills-aptitude-text']?>">
					<?php if (!empty($ST['course_user_details']['date_completed'])){?>
					<b>Session date <?php echo date('d.m.Y', strtotime($ST['course_user_details']['date_completed']))?></b>
					<?php }else{?>
					ILT Session
					<?php }?>
				</div>
			</div>
			<div style="clear:both"></div>
		</div>

		<br><br><br>
		
		<h1 class="paragraph-title" style="<?php echo $style['.paragraph-title']?>">
			EVALUATOR COMMENTS
		</h1>
		<div class="level-scale-container" style="<?php echo $style['.level-scale-container']?>">
			<h2 class="paragraph-subtitle" style="<?php echo $style['.paragraph-subtitle']?>">SKILLS:</h2>
			<?php if (!$isRO){?>
			<textarea name="evaluator_comments" id="evaluator_comments" style="<?php echo $style['#evaluator_comments']?>"><?php
			if (!empty($ReportContent['evaluator_comments']['value']))
				echo $ReportContent['evaluator_comments']['value'];
			?></textarea>
			<?php }elseif (!empty($ReportContent['evaluator_comments']['value'])){?>
			<div style="font-size:12px;">
				<?php echo nl2br($ReportContent['evaluator_comments']['value']);?>
			</div>
			<?php }?>
		</div>
		
		<br><br><br>
		
		<h1 class="paragraph-title" style="<?php echo $style['.paragraph-title']?>">
			SKILL’S LEVEL
		</h1>
		<div class="level-scale-container" style="<?php echo $style['.level-scale-container']?>">
			<h2 class="paragraph-subtitle" style="<?php echo $style['.paragraph-subtitle']?>">SKILLS:</h2>
			<div>Learner's current level for each of the skills below:</div>
			<div class="level-scale-container" style="<?php echo $style['.level-scale-container']?>">
				<?php foreach (array(
					'listening_current_level'	=>'Listening:',
					'speaking_current_level'	=>'Speaking:',
					'reading_current_level'		=>'Reading:',
					'writing_current_level'		=>'Writing:',
				) as $key=>$text){?>
				<div class="level-spacing" style="<?php echo $style['.level-spacing']?>">
					<label for="<?php echo $key?>" class="level-label" style="<?php echo $style['.level-label']?>"><?php echo $text?></label>
					<?php if (!$isRO){?>
					<select id="<?php echo $key?>" name="<?php echo $key?>" class="level-scale" style="<?php echo $style['.level-scale']?>">
						<option></option>
						<?php foreach ($LvlScale as $lK=>$lT){?>
						<option value="<?php echo $lK?>"<?php
							if (!empty($ReportContent[$key]['value']) && $ReportContent[$key]['value']==$lK)
								echo ' selected';
						?>><?php echo $lT?></option>
						<?php }?>
					</select>
					<?php }elseif (!empty($LvlScale[$ReportContent[$key]['value']])){?>
					&nbsp;
					<span class="profile-value" style="<?php echo $style['.profile-value']?>"><?php
						echo $LvlScale[$ReportContent[$key]['value']];?></span>
					<?php }?>
				</div>
				<?php }?>
			</div>
		</div>
		
		<br><br><br>
		
		<h1 class="paragraph-title" style="<?php echo $style['.paragraph-title']?>">
			Learner’s level
		</h1>
		<div class="level-scale-container" style="<?php echo $style['.level-scale-container']?>">
			<br>
			<div>Learner's overall current and recommended levels:</div>
			<div class="level-scale-container" style="<?php echo $style['.level-scale-container']?>">
				<?php foreach (array(
					'learner_self_level'		=>'Self-evaluation level:',
					'learner_current_level'		=>'Current level:',
					'learner_recommended_level'	=>'Recommended level:',
				) as $key=>$text){?>
				<div class="level-spacing" style="<?php echo $style['.level-spacing']?>">
					<label for="<?php echo $key?>" class="level-label" style="<?php echo $style['.level-label']?>"><?php echo $text?></label>
					<?php if (!$isRO){?>
					<select id="<?php echo $key?>" name="<?php echo $key?>" class="level-scale" style="<?php echo $style['.level-scale']?>">
						<option></option>
						<?php foreach ($LvlScale as $lK=>$lT){?>
						<option value="<?php echo $lK?>"<?php
							if (!empty($ReportContent[$key]['value']) && $ReportContent[$key]['value']==$lK)
								echo ' selected';
						?>><?php echo $lT?></option>
						<?php }?>
					</select>
					<?php }elseif (!empty($LvlScale[$ReportContent[$key]['value']])){?>
					&nbsp;
					<span class="profile-value" style="<?php echo $style['.profile-value']?>"><?php echo $LvlScale[$ReportContent[$key]['value']];?></span>
					<?php }?>
				</div>
				<?php }?>
			</div>
		</div>
	</div>
</div>