<?php
$view->getMetaView()->_tpl_version = '1.0';//Defining this template version

$isRO = (!empty($_REQUEST['report_mode']) && strtolower($_REQUEST['report_mode'])==='r');//Is it on read only mode?

$LvlScale = $acquiredLevels = $recommendedLevels = $ReportContent = array();//Declare some useful array

$LP = !empty($view->RpData) ? $view->RpData : null;//Set full data

if (empty($LP['success']))
	echo $view->getBlock('blocks/fer/throwError', array('Data'=>$LP));//Display error block
elseif (isset($LP['learning_plan_final_evaluation']) && is_array($LP['learning_plan_final_evaluation'])){
	foreach ($LP['learning_plan_final_evaluation'] as $reportField){
		if (!empty($reportField['id']))
			$ReportContent[$reportField['id']] = $reportField;//Fill in the array that contains the custom fields for the report
	}
}
$User = !empty($LP['user_profile']) ? $LP['user_profile'] : null;
## Level scale
if (!empty($LP['level_scale'])){
	foreach ($LP['level_scale'] as $i=>$lvl)
		$LvlScale[$lvl['id']] = $lvl['name'];
}
# Temporary : set all acquired and recommended levels in hard code taken from the LMS due to data missing from ETime
$acquiredLevels = array(
	1117 => 'A1.1',
	1118 => 'A1.2',
	1119 => 'A1.3',
	1120 => 'A1.4',
	1121 => 'A2.1',
	1122 => 'A2.2',
	1123 => 'A2.3',
	1124 => 'A2.4',
	1125 => 'A2.5',
	1126 => 'A2.6',
	1127 => 'B1.1',
	1128 => 'B1.2',
	1129 => 'B1.3',
	1130 => 'B1.4',
	1131 => 'B1.5',
	1132 => 'B1.6',
	1133 => 'B2.1',
	1134 => 'B2.2',
	1135 => 'B2.3',
	1136 => 'B2.4',
	1137 => 'B2.5',
	1138 => 'B2.6',
	1139 => 'C1.1',
	1140 => 'C1.2',
	1141 => 'C1.3',
	1142 => 'C1.4',
	1143 => 'C2',
);
$recommendedLevels = array(
	1322 => 'A1.1',
	1323 => 'A1.2',
	1324 => 'A1.3',
	1325 => 'A1.4',
	1326 => 'A2.1',
	1327 => 'A2.2',
	1328 => 'A2.3',
	1329 => 'A2.4',
	1330 => 'A2.5',
	1331 => 'A2.6',
	1332 => 'B1.1',
	1333 => 'B1.2',
	1334 => 'B1.3',
	1335 => 'B1.4',
	1336 => 'B1.5',
	1337 => 'B1.6',
	1338 => 'B2.1',
	1339 => 'B2.2',
	1340 => 'B2.3',
	1341 => 'B2.4',
	1342 => 'B2.5',
	1343 => 'B2.6',
	1344 => 'C1.1',
	1345 => 'C1.2',
	1346 => 'C1.3',
	1347 => 'C1.4',
	1348 => 'C2',
);
if (empty($LvlScale)) $LvlScale = $recommendedLevels;
$levelSelectors = $LvlScale;
if (count($levelSelectors)<count($recommendedLevels))
	$levelSelectors = $recommendedLevels;
## Itest's Levels
$ITLvls = array(
	1 => 'A1.2',
	2 => 'A1.4',
	3 => 'A2.2',
	4 => 'A2.4',
	5 => 'A2.6',
	6 => 'B1.2',
	7 => 'B1.4',
	8 => 'B1.6',
	9 => 'B2.2',
	10 => 'B2.4',
	11 => 'B2.6',
	12 => 'C1.2',
	13 => 'C1.4',
	14 => 'C2',
);
$refererBaseUrl = 'https://www.yesnyoulearning.com';
if (!empty($_SERVER['HTTP_REFERER'])){
	if (stripos('/lms/', $_SERVER['HTTP_REFERER'])!==false){
		$expUrl = explode('/lms/', $_SERVER['HTTP_REFERER']);
		if (!empty($expUrl))
			$refererBaseUrl = $expUrl[0];
	}
}
/**
 * Unfortunately, we need to set all the CSS inline. Using a PHP hack
 */
$style = array(
	'#report_container'		=>'background:white;text-align:left;padding: 20px 0;font-family:Arial;font-size: 13px;',
	'#report_subcontainer'	=>'margin:auto;width:98%;font-family:Arial;',
	'#evaluator_comments'	=>'background:white;width:100%;min-width:100%;max-width:100%;height:120px;border:1px solid rgb(225,225,225);padding:10px;font-family:Arial;',
	'.paragraph-title'		=>'text-transform:uppercase;margin:15px 0;font-weight:normal;font-size:16px;font-family:Arial;color:rgb(86,86,86)',
	'.paragraph-subtitle'	=>'font-size:14px;text-transform:uppercase;margin:0;margin-bottom:15px;font-weight:bold;color:black;font-family:Arial;',
	'.profile-block'		=>'padding:2.5%;width:95%;margin:auto;font-family:Arial;',
	'table'					=>'border-collapse:collapse;width:100%;font-family:Arial;',
	'td'					=>'padding:10px 5px;font-size:13px;font-family:Arial;',
	'.profile-label'		=>'width:100px;text-transform:uppercase;font-size:13px;',
	'.profile-value'		=>'font-weight:bold;font-family:Arial;font-size:12px;',
	'.bg-grey'				=>'background:rgb(233,233,233);font-family: Arial;',
	'.level-scale-container'=>'background:rgb(237,237,237);padding: 25px;font-family:Arial;',
	'.level-spacing'		=>'padding:30px 0 0 60px;',
	'.level-label'			=>'width:5%;white-space:nowrap;font-size:13px;text-transform:uppercase;color:rgb(86,86,86);font-family:Arial;',
	'.level-scale'			=>'width:90%;height:30px;background:white;border:none;padding-left:20px;font-family:Arial;',
	'.skills-aptitude-block'=>'position:relative;min-height:50px;padding:30px 0px;white-space:normal;border-bottom:1px solid rgb(50,50,50);clear:both;',
	'.skills-aptitude-number'=>'background:rgb(87,87,87);display:block;width:55px;line-height:55px;height:55px;font-size:26px;font-weight:bold;'.
								'text-align:center;border-radius:40px;color:white;margin:auto;',
	'.skills-aptitude-title'=>'font-weight:bold;font-size:14px;margin:0;text-transform:uppercase;',
	'.skills-aptitude-text'	=>'font-size:13px;margin-top:5px;',
	'.float-first-block'	=>'float:left;width:120px;overflow:hidden;white-space:nowrap;',
	'.float-second-block'	=>'float:left;max-width:75%;',
	'.sub-text'				=>'color:rgb(86,86,86)',
);?>
<div id="report_container" style="<?php echo $style['#report_container']?>">
	<div style="text-align:center"><?php echo $view->getBlock('fer/images/logo-1');?></div>
	<br>
	<div id="report_subcontainer" style="<?php echo $style['#report_subcontainer']?>">
		<h1 class="paragraph-title" style="<?php echo $style['.paragraph-title']?>">
			PROFILE
		</h1>
		<div style="background:white;">
			<table style="<?php echo $style['table']?>">
				<tr>
					<td class="profile-label" style="<?php echo $style['td'].$style['.profile-label']?>">Learner:</td>
					<td class="profile-value" style="<?php echo $style['td'].$style['.profile-value']?>">
						<?php echo !empty($User['firstname']) ? $User['firstname'].'&nbsp;' : '';?>
						<?php echo !empty($User['lastname']) ? $User['lastname'] : '';?>
					</td>
					<td class="profile-label" style="<?php echo $style['td'].$style['.profile-label']?>">LEVEL:</td>
					<td class="profile-value" colspan="3" style="<?php echo $style['td'].$style['.profile-value']?>"><?php
						$level = null;
						if (!empty($User['fields']) && is_array($User['fields'])){
							foreach ($User['fields'] as $i=>$field){
								if (!empty($field['name']) && !empty($field['value']) && strtolower($field['name'])=='recommended level'){
									$level = $field['value'];
									break;
								}
							}
							if (!$level){
								foreach ($User['fields'] as $i=>$field){
									if (!empty($field['name']) && !empty($field['value']) && strtolower($field['name'])=='acquired level'){
										$level = $field['value'];
										break;
									}
								}
							}
						}
						echo !empty($recommendedLevels[$level]) ? $recommendedLevels[$level] :
								(!empty($LvlScale[$level]) ? $LvlScale[$level] : 
										(!empty($acquiredLevels[$level]) ? $acquiredLevels[$level] : $level));?>
					</td>
				</tr>
				<tr>
					<td class="profile-label" style="<?php echo $style['td'].$style['.profile-label']?>">Company:</td>
					<td class="profile-value" style="<?php echo $style['td'].$style['.profile-value']?>"><?php
					if (!empty($User['fields']) && is_array($User['fields'])){
						foreach ($User['fields'] as $i=>$field){
							if (!empty($field['name']) && !empty($field['value']) && strtolower($field['name'])==='company name'){
								echo $field['value'];
								break;
							}
						}
					}?></td>
					<td class="profile-label" style="<?php echo $style['td'].$style['.profile-label']?>">Start date:</td>
					<td class="profile-value" style="<?php echo $style['td'].$style['.profile-value']?>"><?php
						$date_begin = !empty($LP['learning_plan_user_details']['date_assign']) ? $LP['learning_plan_user_details']['date_assign'] :
							(!empty($LP['learning_plan_user_details']['date_begin_validity']) ? $LP['learning_plan_user_details']['date_begin_validity'] : null);
						echo $date_begin ? date('d.m.Y', strtotime($date_begin)) : '&nbsp;';?></td>
					<td class="profile-label" style="<?php echo $style['td'].$style['.profile-label']?>">End date:</td>
					<td class="profile-value" style="<?php echo $style['td'].$style['.profile-value']?>"><?php
						$date_end = !empty($LP['learning_plan_user_details']['course_completed']) ? $LP['learning_plan_user_details']['course_completed'] :
							(!empty($LP['learning_plan_user_details']['date_end_validity']) ? $LP['learning_plan_user_details']['date_end_validity'] : null);
						echo $date_end ? date('d.m.Y', strtotime($date_end)) : '&nbsp;';?></td>
				</tr>
				<tr>
					<td class="profile-label" style="<?php echo $style['td'].$style['.profile-label']?>">Date:</td>
					<td class="profile-value" style="<?php echo $style['td'].$style['.profile-value']?>"><?php echo date('d.m.Y')?></td>
					<td class="profile-label" style="<?php echo $style['td'].$style['.profile-label']?>">Total time:</td>
					<td class="profile-value" style="<?php echo $style['td'].$style['.profile-value']?>"><?php
						//Should be in seconds
						$totaltime = !empty($LP['learning_plan_user_details']['time_spent']) ? (int)$LP['learning_plan_user_details']['time_spent'] : 0;
						if ($totaltime){
							echo gmdate('H:i', $totaltime);
						}?></td>
				</tr>
			</table>
		</div>
		
		<br><br><br>
		
		<h1 class="paragraph-title" style="<?php echo $style['.paragraph-title']?>">
			Language Skills Aptitude Test
		</h1>
		<?php $NA = $IT = $WT = $ST = null;
		foreach ($LP['learning_plan_courses'] as $Course){
			if (!empty($Course['course_info']['course_name'])){
				$coursename = strtolower($Course['course_info']['course_name']);
				if (stripos($coursename, 'needs')!==false)
					$NA = $Course;
				elseif (stripos($coursename, 'written')!==false)
					$WT = $Course;
				elseif (stripos($coursename, 'itest')!==false)
					$IT = $Course;
				elseif (stripos($coursename, 'speaking')!==false)
					$ST = $Course;
			}
		}?>
		<div class="skills-aptitude-block" style="<?php echo $style['.skills-aptitude-block']?>">
			<div style="<?php echo $style['.float-first-block']?>">
				<div class="skills-aptitude-number" style="<?php echo $style['.skills-aptitude-number']?>">
					1
				</div>
			</div>
			<div style="<?php echo $style['.float-second-block']?>">
				<h2 class="skills-aptitude-title" style="<?php echo $style['.skills-aptitude-title']?>">Needs Analysis</h2>
				<div class="skills-aptitude-text" style="<?php echo $style['.skills-aptitude-text']?>">
					<?php if (!empty($NA['course_user_details']['date_completed'])){?>
					<b>Completed <?php echo date('d.m.Y', strtotime($NA['course_user_details']['date_completed']))?></b>
					<?php if (!$isRO){?>
					&nbsp;&nbsp;&nbsp;&nbsp;
					<a href="<?php echo $refererBaseUrl.'/lms/index.php?r=player/report/byUser&course_id='.
						$NA['course_info']['course_id'].'&user_id='.$User['id_user']?>" target="_blank"><i>See all the answers</i></a>
					<?php }?>
					<?php }else{?>
					 -
					<?php }?>
				</div>
			</div>
			<div style="clear:both"></div>
		</div>
		<div class="skills-aptitude-block" style="<?php echo $style['.skills-aptitude-block']?>">
			<div style="<?php echo $style['.float-first-block']?>">
				<div class="skills-aptitude-number" style="<?php echo $style['.skills-aptitude-number']?>">
					2
				</div>
			</div>
			<div style="<?php echo $style['.float-second-block']?>">
				<h2 class="skills-aptitude-title" style="<?php echo $style['.skills-aptitude-title']?>">Written test</h2>
				<div class="skills-aptitude-text" style="<?php echo $style['.skills-aptitude-text']?>">
					<?php if (!empty($WT['course_user_details']['date_completed'])){?>
					<b>Completed <?php echo date('d.m.Y', strtotime($WT['course_user_details']['date_completed']))?></b>
					<?php if (!$isRO){?>
					&nbsp;&nbsp;&nbsp;&nbsp;
					<a href="<?php echo $refererBaseUrl.'/lms/index.php?r=player/report/byUser&course_id='.
						$WT['course_info']['course_id'].'&user_id='.$User['id_user']?>" target="_blank"><i>See all the answers</i></a>
					<?php }?>
					<br><br>
					<i><?php if (!empty($WT['course_training_materials'])){
								foreach ($WT['course_training_materials'] as $material){
									if (!empty($material['training_material_qas'])){
										foreach ($material['training_material_qas'] as $qas){
											if (!empty($qas['user_answer'])){
												foreach ($qas['user_answer'] as $nswr){
													if (!empty($nswr['answer']))
														echo nl2br($nswr['answer']).'<br>';
												}
											}
										}
									}
								}
							}?></i>
					<?php }else{?>
					-
					<?php }?>
				</div>
			</div>
			<div style="clear:both"></div>
		</div>
		<div class="skills-aptitude-block" style="<?php echo $style['.skills-aptitude-block']?>">
			<div style="<?php echo $style['.float-first-block']?>">
				<div class="skills-aptitude-number" style="<?php echo $style['.skills-aptitude-number']?>">
					3
				</div>
			</div>
			<div style="<?php echo $style['.float-second-block']?>">
				<h2 class="skills-aptitude-title" style="<?php echo $style['.skills-aptitude-title']?>">iTest</h2>
				<div class="skills-aptitude-text" style="<?php echo $style['.skills-aptitude-text']?>">
					<?php if (!empty($IT['course_user_details']['date_completed'])){?>
					<b>Completed <?php echo date('d.m.Y', strtotime($IT['course_user_details']['date_completed']))?></b>
					<?php if (!$isRO){?>
					&nbsp;&nbsp;&nbsp;&nbsp;
					<a href="<?php echo $refererBaseUrl.'/lms/index.php?r=player/report/byUser&course_id='.
						$IT['course_info']['course_id'].'&user_id='.$User['id_user']?>" target="_blank"><i>See all the answers</i></a>
					<?php }?>
					<br><br>
					<?php if (!empty($IT['course_user_details']['score_given'])){
						$lvlIx = (int)$IT['course_user_details']['score_given'];
						if (isset($ITLvls[$lvlIx])){?>
					<i>Estimated level is <b><?php echo $ITLvls[$lvlIx]?></b></i>
					<?php }}?>
					<?php }else{?>
					-
					<?php }?>
				</div>
			</div>
			<div style="clear:both"></div>
		</div>
		<div class="skills-aptitude-block" style="<?php echo $style['.skills-aptitude-block']?>">
			<div style="<?php echo $style['.float-first-block']?>">
				<div class="skills-aptitude-number" style="<?php echo $style['.skills-aptitude-number']?>">
					4
				</div>
			</div>
			<div style="<?php echo $style['.float-second-block']?>">
				<h2 class="skills-aptitude-title" style="<?php echo $style['.skills-aptitude-title']?>">Speaking Test</h2>
				<div class="skills-aptitude-text" style="<?php echo $style['.skills-aptitude-text']?>">
					<?php if (!empty($ST['course_sessions'][0]['session_info']['date_end'])){?>
					<b>Session date <?php echo date('d.m.Y', strtotime($ST['course_sessions'][0]['session_info']['date_end']))?></b>
					<?php }else echo ' - ';?>
				</div>
			</div>
			<div style="clear:both"></div>
		</div>

		<br><br><br>
		
		<h1 class="paragraph-title" style="<?php echo $style['.paragraph-title']?>">
			EVALUATOR COMMENTS
		</h1>
		<div class="level-scale-container" style="<?php echo $style['.level-scale-container']?>">
			<h2 class="paragraph-subtitle" style="<?php echo $style['.paragraph-subtitle']?>">SKILLS:</h2>
			<?php if (!$isRO){?>
			<textarea name="evaluator_comments" id="evaluator_comments" style="<?php echo $style['#evaluator_comments']?>"><?php
			if (!empty($ReportContent['evaluator_comments']['value']))
				echo $ReportContent['evaluator_comments']['value'];
			elseif (!empty($ST['course_sessions'][0]['user_session_details']['evaluation_text']))
				echo strip_tags($ST['course_sessions'][0]['user_session_details']['evaluation_text']);
			?></textarea>
			<?php }elseif (!empty($ReportContent['evaluator_comments']['value'])){?>
			<div style="font-size:12px;">
				<?php echo nl2br($ReportContent['evaluator_comments']['value']);?>
			</div>
			<?php }?>
		</div>
		
		<br><br><br>
		
		<h1 class="paragraph-title" style="<?php echo $style['.paragraph-title']?>">
			SKILL’S LEVEL
		</h1>
		<div class="level-scale-container" style="<?php echo $style['.level-scale-container']?>">
			<h2 class="paragraph-subtitle" style="<?php echo $style['.paragraph-subtitle']?>">SKILLS:</h2>
			<div style="<?php echo $style['.sub-text']?>">Learner's current level for each of the skills below:</div>
			<table class="level-scale-container" style="<?php echo $style['table'].$style['.level-scale-container']?>">
				<?php foreach (array(
					'listening_current_level'	=>'Listening:',
					'speaking_current_level'	=>'Speaking:',
					'reading_current_level'		=>'Reading:',
					'writing_current_level'		=>'Writing:',
				) as $key=>$text){?>
				<tr>
					<td style="<?php echo $style['.level-spacing'].$style['.level-label'];?>">
						<label for="<?php echo $key?>" class="level-label"><?php echo strtoupper($text);?></label>
					</td>
					<td style="<?php echo $style['.level-spacing'];?>">
						<?php if (!$isRO){?>
						<select id="<?php echo $key?>" name="<?php echo $key?>" class="level-scale" style="<?php echo $style['.level-scale']?>">
							<option></option>
							<?php foreach ($levelSelectors as $lK=>$lT){?>
							<option value="<?php echo $lK?>"<?php
								if (!empty($ReportContent[$key]['value']) && $ReportContent[$key]['value']==$lK)
									echo ' selected';
							?>><?php echo $lT?></option>
							<?php }?>
						</select>
						<?php }elseif (!empty($levelSelectors[$ReportContent[$key]['value']])){?>
						&nbsp;
						<span class="profile-value" style="<?php echo $style['.profile-value']?>"><?php
							echo $levelSelectors[$ReportContent[$key]['value']];?></span>
						<?php }?>
					</td>
				</tr>
				<?php }?>
			</table>
			<br><br>
		</div>
		
		<br><br><br>
		
		<h1 class="paragraph-title" style="<?php echo $style['.paragraph-title']?>">
			Learner’s level
		</h1>
		<div class="level-scale-container" style="<?php echo $style['.level-scale-container']?>">
			<br>
			<div style="<?php echo $style['.sub-text']?>">Learner's overall current and recommended levels:</div>
			<table class="level-scale-container" style="<?php echo $style['table'].$style['.level-scale-container']?>">
				<?php foreach (array(
					'learner_self_level'=>'Self-evaluation level:',
					'acquired_level'	=>'Current level:',
					'recommended_level'	=>'Recommended level:',
				) as $key=>$text){
					$thisLvlSelector = $levelSelectors;
					if ($key === 'acquired_level')			$thisLvlSelector = $acquiredLevels;
					elseif ($key === 'recommended_level')	$thisLvlSelector = $recommendedLevels;?>
				<tr class="level-spacing" style="<?php echo $style['.level-spacing']?>">
					<td style="<?php echo $style['.level-spacing'].$style['.level-label'];?>">
						<label for="<?php echo $key?>" class="level-label"><?php echo strtoupper($text);?></label>
					</td>
					<td style="<?php echo $style['.level-spacing'];?>">
						<?php if (!$isRO){?>
						<select id="<?php echo $key?>" name="<?php echo $key?>" class="level-scale" style="<?php echo $style['.level-scale']?>">
							<option></option>
							<?php foreach ($thisLvlSelector as $lK=>$lT){?>
							<option value="<?php echo $lK?>"<?php
								if (!empty($ReportContent[$key]['value']) && $ReportContent[$key]['value']==$lK)
									echo ' selected';
							?>><?php echo $lT?></option>
							<?php }?>
						</select>
						<?php }elseif (!empty($thisLvlSelector[$ReportContent[$key]['value']])){?>
						&nbsp;
						<span class="profile-value" style="<?php echo $style['.profile-value']?>"><?php echo $thisLvlSelector[$ReportContent[$key]['value']];?></span>
						<?php }?>
					</td>
				</tr>
				<?php }?>
			</table>
			<br><br>
		</div>
	</div>
</div>