<?php $view->getMetaView()->_tpl_version = '1.0';
$User	= !empty($view->User)	? $view->User	: null;
$LP		= !empty($view->LP)		? $view->LP		: null;
if (empty($User['success']) || empty($LP['success'])) echo $view->getBlock('blocks/fer/throwError', array('User'=>$User, 'LP'=>$LP));?>
<style>
	h1.paragraph-title{
		text-transform: uppercase;
		margin: 15px 0;
	}
	div.profile-inline-block{
		display:inline-block;
		padding:2.5%;
		width:40%;
	}
	div.skills-aptitude-block{
		background:rgb(253,182,105);
		width:90%;
	}
	div.skills-aptitude-number{
		background:rgb(87,87,87);
		display:inline-block;
		width:40px;
		line-height:40px;
		font-size:20px;
		font-weight:bold;
		text-align:center;
		border-radius:40px;
		float:left;
		color:white;
	}
</style>
<div style="background:rgb(236,236,236);text-align:left;padding:30px 0;">
	<div style="margin:auto;width:80%;">
		<h1 class="paragraph-title">
			Profil
		</h1>
		<div style="background:white;">
			<div class="profile-inline-block">
				<table>
					<tr>
						<td>LEARNER:</td>
						<td>
							<?php echo !empty($User['firstname']) ? $User['firstname'] : '';?>
							<?php echo !empty($User['lastname']) ? $User['lastname'] : '';?>
						</td>
					</tr>
					<tr>
						<td>COMPANY:</td>
						<td><?php
						if (!empty($User['fields']) && is_array($User['fields'])){
							foreach ($User['fields'] as $i=>$field){
								if (!empty($field['name']) && !empty($field['value']) && strtolower($field['name'])==='company name'){
									echo $field['value'];
									break;
								}
							}
						}?></td>
					</tr>
					<tr>
						<td>DATE:</td>
						<td><?php echo date('d.m.Y')?></td>
					</tr>
				</table>
			</div>
			<div class="profile-inline-block">
				<table>
					<tr>
						<td>LEVEL:</td>
						<td><?php
						$level = null;
						/*if (!empty($User['fields']) && is_array($User['fields'])){
							foreach ($User['fields'] as $i=>$field){
								if (!empty($field['name']) && !empty($field['value']) && in_array(strtolower($field['name']), array('acquired level', 'recommended level'))){
									$level = $field['value'];
									break;
								}
							}
						}*/
						if (!$level){
							//Match it into the learning plan path name
							if (!empty($LP['learning_plan']['path_name'])){
								$terms = explode(' ', $LP['learning_plan']['path_name']);
								if ($terms && strlen($terms[0])>1){
									$suspectedLvl = $terms[0];
									$letterLvl = strtoupper(substr($suspectedLvl, 0, 1));
									$numberLvl = substr($suspectedLvl, 1, 1);
									if (in_array($letterLvl, array('A', 'B', 'C')) && in_array($numberLvl, array('1','2','3'))){
										$level = strtoupper($suspectedLvl);
									}
								}
							}
						}
						echo $level;
						?></td>
					</tr>
					<tr>
						<td>START DATE:</td>
						<td><?php echo !empty($LP['learning_plan']['learning_plan_user_details']['date_assign']) ? $LP['learning_plan']['learning_plan_user_details']['date_assign'] :
						(
								!empty($LP['learning_plan']['learning_plan_user_details']['date_begin_validity']) ? $LP['learning_plan']['learning_plan_user_details']['date_begin_validity'] : ''
						);?></td>
						<td>END DATE:</td>
						<td><?php echo !empty($LP['learning_plan']['learning_plan_user_details']['course_completed']) ? $LP['learning_plan']['learning_plan_user_details']['course_completed'] :
						(
								!empty($LP['learning_plan']['learning_plan_user_details']['date_end_validity']) ? $LP['learning_plan']['learning_plan_user_details']['date_end_validity'] : ''
						);?></td>
					</tr>
					<tr>
						<td>TOTAL TIME:</td>
						<td><?php echo !empty($LP['learning_plan']['learning_plan_user_details']['time_spent']) ? $LP['learning_plan']['learning_plan_user_details']['time_spent'] : '';?></td>
					</tr>
				</table>
			</div>
		</div>
		
		<h1 class="paragraph-title">
			Language Skills Aptitude Test
		</h1>
		<table style="width:100%;">
			<tr>
				<td style="width:50%;">
					<div class="skills-aptitude-block">
						<div class="skills-aptitude-number">
							1
						</div>
						<h2 style="">Needs Analysis</h2>
						<span style="font-style:italic;">Elearning DOCEBO “Survey”</span>
					</div>
				</td>
				<td style="width:50%;">
					<div class="skills-aptitude-block">
						<div class="skills-aptitude-number">
							2
						</div>
						<h2 style="">Needs Analysis</h2>
						<span style="font-style:italic;">Elearning DOCEBO “Survey”</span>
					</div>
				</td>
			</tr>
			<tr>
				<td>
					<div class="skills-aptitude-block">
						<div class="skills-aptitude-number">
							3
						</div>
						<h2 style="">Needs Analysis</h2>
						<span style="font-style:italic;">Elearning DOCEBO “Survey”</span>
					</div>
				</td>
				<td>
					<div class="skills-aptitude-block">
						<div class="skills-aptitude-number">
							4
						</div>
						<h2 style="">Needs Analysis</h2>
						<span style="font-style:italic;">Elearning DOCEBO “Survey”</span>
					</div>
				</td>
			</tr>
		</table>
		<form method="post">
			<h1 class="paragraph-title">
				EVALUATOR COMMENTS
			</h1>
			<div style="background:white;">
				<h3>SKILLS:</h3>
				<textarea style="width:99%;height:45px;" name="evaluator_comments"></textarea>
			</div>
			
			<h1 class="paragraph-title">
				SKILL’S LEVEL
			</h1>
			Etc.
		
		</form>
	</div>
</div>
<?php if (defined('ENV') && ENV==='devel'){?>
<pre style="text-align:left"><?php print_r(array('User'=>$User, 'LP'=>$LP))?></pre>
<?php }?>