<style>
	h1.paragraph-title{
		text-transform: uppercase;
		margin: 15px 0;
	}
	div.profile-inline-block{
		display:inline-block;
		padding:2.5%;
		width:40%;
	}
	div.skills-aptitude-block{
		background:rgb(253,182,105);
		width:90%;
	}
	div.skills-aptitude-number{
		background:rgb(87,87,87);
		display:inline-block;
		width:40px;
		line-height:40px;
		font-size:20px;
		font-weight:bold;
		text-align:center;
		border-radius:40px;
		float:left;
		color:white;
	}
</style>
<div style="background:rgb(236,236,236);text-align:left;padding:30px 0;">
	<div style="margin:auto;width:80%;">
		<h1 class="paragraph-title">
			Profil
		</h1>
		<div style="background:white;">
			<div class="profile-inline-block">
				<table>
					<tr>
						<td>LEARNER:</td>
						<td></td>
					</tr>
					<tr>
						<td>COMPANY:</td>
						<td></td>
					</tr>
					<tr>
						<td>DATE:</td>
						<td></td>
					</tr>
				</table>
			</div>
			<div class="profile-inline-block">
				<table>
					<tr>
						<td>LEVEL:</td>
						<td></td>
					</tr>
					<tr>
						<td>START DATE:</td>
						<td></td>
						<td>END DATE:</td>
						<td></td>
					</tr>
					<tr>
						<td>TOTAL TIME:</td>
						<td></td>
					</tr>
				</table>
			</div>
		</div>
		
		<h1 class="paragraph-title">
			Language Skills Aptitude Test
		</h1>
		<table style="width:100%;">
			<tr>
				<td style="width:50%;">
					<div class="skills-aptitude-block">
						<div class="skills-aptitude-number">
							1
						</div>
						<h2 style="">Needs Analysis</h2>
						<span style="font-style:italic;">Elearning DOCEBO “Survey”</span>
					</div>
				</td>
				<td style="width:50%;">
					<div class="skills-aptitude-block">
						<div class="skills-aptitude-number">
							2
						</div>
						<h2 style="">Needs Analysis</h2>
						<span style="font-style:italic;">Elearning DOCEBO “Survey”</span>
					</div>
				</td>
			</tr>
			<tr>
				<td>
					<div class="skills-aptitude-block">
						<div class="skills-aptitude-number">
							3
						</div>
						<h2 style="">Needs Analysis</h2>
						<span style="font-style:italic;">Elearning DOCEBO “Survey”</span>
					</div>
				</td>
				<td>
					<div class="skills-aptitude-block">
						<div class="skills-aptitude-number">
							4
						</div>
						<h2 style="">Needs Analysis</h2>
						<span style="font-style:italic;">Elearning DOCEBO “Survey”</span>
					</div>
				</td>
			</tr>
		</table>
		<form method="post">
			<h1 class="paragraph-title">
				EVALUATOR COMMENTS
			</h1>
			<div style="background:white;">
				<h3>SKILLS:</h3>
				<textarea style="width:99%;height:45px;" name="evaluator_comments"></textarea>
			</div>
			
			<h1 class="paragraph-title">
				SKILL’S LEVEL
			</h1>
			Etc.
		
		</form>
	</div>
</div>