<div style="font-style: italic">
	<?php echo _('Message sent from the website').' '.WEB_ROOT;?>
</div>
<p style="font-weight:bold"><?php echo _('Hi there!');?></p>
<p><?php echo _('You have to click the link below to finish your password recovery process.');?></p>
<div>
	<a href="<?php echo ADMIN_WEB_ROOT?>/user/password_recovery?auth_key=<?php echo $view->message?>">
		<?php echo _('Please, click here')?>
	</a>
</div>
<?php echo $view->getBlock('mail/mail-footer');
