<?php echo nl2br($view->message)?>
<div><?php echo _('An account deletion means that all your data have previously been permanently deleted either by yourself or by an administrator.')?></div>
<div><?php echo _('If you decide to create a new account on our website, it will not be possible to recover your ancient data.')?></div>
<div><?php echo _('Thank you for your interest on this website.')?></div>
<div><?php echo _('Best regards,')?></div>
<?php echo $view->getBlock('mail/mail-footer');
