<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title><?php echo $view->getTitle()?></title>
		<?php echo $view->getCssTags()?>
	</head>
	<body>
		<?php echo $view;?>
		<?php echo $view->getJsTags()?>
	</body>
</html>