<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title><?php echo $view->getTitle()?></title>
		<?php echo $view->getCssTags()?>
		<!--[if IE]>
			<link rel="stylesheet" type="text/css" href="<?php echo WEB_ROOT?>/css/ie.css" />
		<![endif]-->
	</head>
	
	<body class="<?php echo $myCurrentView = str_replace('/', ' ', $view->getViewName());?> <?php
		$getMyCurrentView = str_replace('/', ' ', $_GET['my_current_view']);
		if ($myCurrentView!=$getMyCurrentView) echo $getMyCurrentView;?>">
		<div class="page">
			<section class="content">
				<?php echo $view->getUserEndMsgs()?>
				<?php echo $view;?>
			</section>
		</div>
		<script type="text/javascript" src="<?php echo WEB_ROOT?>/js/jquery.min.js"></script>		
		<!--[if lte IE 8]>
			<script type="text/javascript" src="http://code.jquery.com/jquery-1.11.2.min.js"></script>
		<![endif]-->
		<?php echo $view->getJsTags()?>
	</body>
</html>