<?php
$props['type']	= 'text';
$props['class']	= 'ss_number'.(!empty($view->class) ? ' '.$view->class : '');
foreach (array('id', 'required', 'readonly', 'disabled', 'value', 'name', 'title', 'style', 'placeholder', 'addedprops') as $key)
	if (isset($view->$key)) $props[$key] = $view->$key;
$props['addedprops']['pattern']	= '[12][ \.\-]?[0-9]{2}[ \.\-]?(0[1-9]|[1][0-2])[ \.\-]?([0-9]{2}|2A|2B)[ \.\-]?[0-9]{3}[ \.\-]?[0-9]{3}[ \.\-]?[0-9]{2}';
$props['maxlength'] = 21;
echo $view->getBlock('blocks/inputs/input', $props);